// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiApp;

#nullable disable

namespace TaxiApp.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TaxiApp.Models.Buyurtma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HaydovchiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MijozId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Narx")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qayerdan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Qayerga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HaydovchiId");

                    b.HasIndex("MijozId");

                    b.ToTable("Buyurtmalar");
                });

            modelBuilder.Entity("TaxiApp.Models.Haydovchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Holati")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ismi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MashinaRaqami")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Haydovchilar");
                });

            modelBuilder.Entity("TaxiApp.Models.Mijoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ismi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mijozlar");
                });

            modelBuilder.Entity("TaxiApp.Models.Buyurtma", b =>
                {
                    b.HasOne("TaxiApp.Models.Haydovchi", "Haydovchi")
                        .WithMany("Buyurtmalar")
                        .HasForeignKey("HaydovchiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiApp.Models.Mijoz", "Mijoz")
                        .WithMany("Buyurtmalar")
                        .HasForeignKey("MijozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Haydovchi");

                    b.Navigation("Mijoz");
                });

            modelBuilder.Entity("TaxiApp.Models.Haydovchi", b =>
                {
                    b.Navigation("Buyurtmalar");
                });

            modelBuilder.Entity("TaxiApp.Models.Mijoz", b =>
                {
                    b.Navigation("Buyurtmalar");
                });
#pragma warning restore 612, 618
        }
    }
}
